import os
import logging
import soundfile as sf
import numpy as np

logger = logging.getLogger(__name__)

def synthesize_speech(
    text: str,
    output_path: str,
    use_mlx: bool = False,
    speed: float = 1.0,
    stream: bool = False,
    temperature: float = 0.7,
    top_p: float = 0.95,
    repetition_penalty: float = 1.2,
) -> str:
    """
    Synthesize speech using the Soprano-1.1-80M model.
    """
    if use_mlx:
        return _synthesize_mlx(text, output_path, speed, stream, temperature, top_p)
    else:
        return _synthesize_torch(text, output_path, speed, stream, temperature, top_p, repetition_penalty)

def _synthesize_torch(text, output_path, speed, stream, temperature, top_p, repetition_penalty):
    try:
        from soprano import SopranoTTS
        from soprano.utils.streaming import play_stream
        import torch
        
        model = SopranoTTS(backend='auto', device='auto')
        sample_rate = 32000 # Soprano uses 32kHz
        
        if stream:
            logger.info("Starting smooth streaming generation (Torch)...")
            generator = model.infer_stream(
                text=text,
                top_p=top_p,
                temperature=temperature,
                repetition_penalty=repetition_penalty,
                chunk_size=1
            )
            
            # We need to collect all audio to save to output_path at the end
            # but play_stream consumes the generator.
            # We'll wrap the generator to collect chunks.
            all_audio = []
            def collector_gen():
                for chunk in generator:
                    if chunk is not None:
                        # chunk is a torch.Tensor
                        audio_np = chunk.cpu().numpy().astype(np.float32)
                        all_audio.append(audio_np)
                        yield chunk
            
            play_stream(collector_gen(), sample_rate=sample_rate)
        else:
            model.infer(
                text=text,
                out_path=output_path,
                top_p=top_p,
                temperature=temperature,
                repetition_penalty=repetition_penalty
            )
            # Read back for speed adjustment if needed
            if speed != 1.0:
                _apply_speed(output_path, speed)
            return output_path

        if not all_audio:
            raise ValueError("No audio generated by Soprano Torch")
            
        full_audio = np.concatenate(all_audio)
        sf.write(output_path, full_audio, sample_rate)
        
        if speed != 1.0:
            _apply_speed(output_path, speed)
            
        return output_path
    except ImportError:
        logger.error("soprano-tts not installed.")
        raise
    except Exception as e:
        logger.error(f"Soprano Torch synthesis failed: {e}")
        raise

def _synthesize_mlx(text, output_path, speed, stream, temperature, top_p):
    try:
        import mlx.core as mx
        from mlx_audio.tts.utils import load_model
        import sounddevice as sd
        model_id = "mlx-community/Soprano-80M-6bit"
        
        model = load_model(model_id)
        sample_rate = model.sample_rate
        
        generator = model.generate(
            text=text,
            temperature=temperature,
            top_p=top_p
        )
        
        all_audio = []
        
        if stream:
            logger.info("Starting smooth streaming generation (MLX)...")
            with sd.OutputStream(
                samplerate=sample_rate,
                channels=1,
                dtype='float32',
                blocksize=0
            ) as out_stream:
                for res in generator:
                    if res.audio is not None:
                        audio_np = np.array(res.audio).astype(np.float32)
                        all_audio.append(audio_np)
                        
                        # Ensure shape (N, 1) for sounddevice
                        chunk = audio_np
                        if chunk.ndim == 1:
                            chunk = chunk[:, np.newaxis]
                        
                        out_stream.write(chunk)
        else:
            for res in generator:
                if res.audio is not None:
                    audio_np = np.array(res.audio)
                    all_audio.append(audio_np)
            
        if not all_audio:
            raise ValueError("No audio generated by MLX Soprano")
            
        full_audio = np.concatenate(all_audio)
        sf.write(output_path, full_audio, sample_rate)

        if speed != 1.0:
            _apply_speed(output_path, speed)

        return output_path
        
    except Exception as e:
        logger.warning(f"MLX synthesis failed or not available, falling back to Torch: {e}")
        return _synthesize_torch(text, output_path, speed, stream, temperature, top_p, 1.2)

def _apply_speed(path, speed):
    try:
        import librosa
        import soundfile as sf
        audio, sr = librosa.load(path, sr=None)
        if speed != 1.0:
            audio_fast = librosa.effects.time_stretch(audio, rate=speed)
            sf.write(path, audio_fast, sr)
    except Exception as e:
        logger.error(f"Failed to apply speed adjustment: {e}")
